/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.MenuData;
import Entidades.MenuPension;
import javax.swing.JOptionPane;


/**
 *
 * @author I36100
 */
public class seleccionarMenu extends javax.swing.JInternalFrame {
public static MenuPension menuSeleccionado;
MenuData menuData = new MenuData();
    /**
     * Creates new form seleccionarMenu
     */
    public seleccionarMenu() {
        initComponents();
        cargarComboBox();
       tfCosto.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlSeleccionar = new javax.swing.JLabel();
        jcbtipoMenu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jbSiguiente = new javax.swing.JButton();
        tfCosto = new javax.swing.JTextField();

        setClosable(true);

        jlSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jlSeleccionar.setText("Selecciona tu Menu");

        jcbtipoMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbtipoMenuItemStateChanged(evt);
            }
        });
        jcbtipoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbtipoMenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Costo");

        jbAgregar.setText("Agregar al paquete");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbSiguiente.setText("Siguente ➡️");
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(164, 164, 164))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jbAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jbSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbtipoMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlSeleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlSeleccionar)
                .addGap(18, 18, 18)
                .addComponent(jcbtipoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jbSiguiente))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbtipoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbtipoMenuActionPerformed
    
    }//GEN-LAST:event_jcbtipoMenuActionPerformed

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
       PasajeView v = new PasajeView();
       v.setVisible(true);
       Menu.escritorio.add(v);
       this.dispose();
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        String tipo =  (String) jcbtipoMenu.getSelectedItem();
        double costo = Double.parseDouble(tfCosto.getText());
        menuSeleccionado = new MenuPension(tipo,costo); 
        if(menuSeleccionado !=null){
            JOptionPane.showMessageDialog(this, "Menu agregado al paquete");
        }else{
            JOptionPane.showMessageDialog(this, "Error al intentar agregar al paquete.");
            return;
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void jcbtipoMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbtipoMenuItemStateChanged
 if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String tipo = (String) jcbtipoMenu.getSelectedItem();
        MenuPension menu = menuData.buscarMenuPorTipo(tipo);
        if (menu != null) {
            tfCosto.setText(String.valueOf(menu.getPorcentaje()));
        }
    }
    }//GEN-LAST:event_jcbtipoMenuItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbSiguiente;
    private javax.swing.JComboBox<String> jcbtipoMenu;
    private javax.swing.JLabel jlSeleccionar;
    private javax.swing.JTextField tfCosto;
    // End of variables declaration//GEN-END:variables

public void cargarComboBox(){
     jcbtipoMenu.removeAllItems();
    tfCosto.setText("");
    for(MenuPension m : menuData.listarMenus()){
        jcbtipoMenu.addItem(m.getTipo());

    }    
}

}
