/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author fedeg
 */
import AccesoADatos.PaqueteData;
import Entidades.PaqueteDetalle;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.table.DefaultTableModel;

public class vistaCancelarPaquete extends javax.swing.JInternalFrame {
private final PaqueteData paqueteData = new PaqueteData();
private boolean modificable = false;
    /**
     * Creates new form vistaCancelarPaquete
     */
    public vistaCancelarPaquete() {
        initComponents();
         jbModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jbVerificar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        tfID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese ID");
        jInternalFrame1.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 70, 30));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Origen", "Destino", "Fecha de inicio", "Fecha Fin", "Nombre Alojamiento", "Direccion Alojamiento", "Menu", "Transporte", "Pasajeros", "Medio de pago", "Precio Total", "Pagado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jInternalFrame1.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1010, 280));

        jbVerificar.setText("Verificar");
        jbVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerificarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 180, 40));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 150, 40));

        tfID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfIDKeyReleased(evt);
            }
        });
        jInternalFrame1.getContentPane().add(tfID, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 160, -1));

        jLabel2.setText("CANCELAR UN PAQUETE");
        jInternalFrame1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 210, 40));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    private void jbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarActionPerformed
          int filaSeleccionada = tabla.getSelectedRow();
    if (filaSeleccionada >= 0) {
        // Obtener la fecha como objeto Date
        Object fechaObj = tabla.getValueAt(filaSeleccionada, 2); // Columna 2 es la fecha de inicio
        String fechaInicio = null;

        // Verificar si el objeto es de tipo Date
        if (fechaObj instanceof java.util.Date) {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            fechaInicio = formatoFecha.format((java.util.Date) fechaObj);
        }

        // Validar si la conversión fue exitosa
        if (fechaInicio != null && !verificarAnticipacionDeDias(fechaInicio)) {
            JOptionPane.showMessageDialog(this, "El inicio del viaje debe ser al menos 30 días después de hoy.");
            return;
        }

        // Modificar el paquete
        JOptionPane.showMessageDialog(this, "Paquete válido para modificar. Continúa con los cambios necesarios.");
        modificable = true;
        jbModificar.setEnabled(true);
        jbVerificar.setEnabled(false);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione un paquete para modificar.");
    }
    }//GEN-LAST:event_jbVerificarActionPerformed

    private void tfIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIDKeyReleased
        mostrarPaquetes();
    }//GEN-LAST:event_tfIDKeyReleased

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if(modificable){
            int id = Integer.parseInt(tfID.getText());
             paqueteData.cancelarPaquete(id);
             jbModificar.setEnabled(false);
             jbVerificar.setEnabled(true);
             tfID.setText("");
              DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
             modeloTabla.setRowCount(0);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCancelarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCancelarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCancelarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCancelarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCancelarPaquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbVerificar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField tfID;
    // End of variables declaration//GEN-END:variables
  private boolean verificarAnticipacionDeDias(String fInicio) {
        try {
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy");
            Date fechaInicio = formatoFecha.parse(fInicio);
            Date fechaActual = new Date();

            long diferenciaEnMilis = fechaInicio.getTime() - fechaActual.getTime();
            long diasDiferencia = TimeUnit.DAYS.convert(diferenciaEnMilis, TimeUnit.MILLISECONDS);

            return diasDiferencia >= 30;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al verificar la fecha de inicio: " + e.getMessage());
            return false;
        }
    }
  
  private void mostrarPaquetes(){
      try{
      int id = Integer.parseInt(tfID.getText());
      DefaultTableModel modeloTabla = (DefaultTableModel) tabla.getModel();
      modeloTabla.setRowCount(0);
     for(PaqueteDetalle p : paqueteData.obtenerDetallePaquetes(id)){
         modeloTabla.addRow(new Object[]{p.getCiudadOrigen(), p.getCiudaDestino(), p.getFechaInicio(), p.getFechaFin(), p.getNombreAlojamiento(), p.getDireccionAlojamiento(),
         p.getTipoMenu(),p.getTipoTransporte(),p.getCantidadPasajeros(),p.getMedioPago(),p.getPrecioTotal(),p.isPagado()});
     }
      }catch(NumberFormatException ex){
          JOptionPane.showMessageDialog(this, "Debe ingresar un ID válido");
      }
      
      
  }
}
