/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Vic-G5
 */
public class vistaPaqueteFijo extends javax.swing.JInternalFrame {

    /**
     * Creates new form vistaPaqueteFijo
     */
    public vistaPaqueteFijo() {
        initComponents();
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        panelGeneral = new javax.swing.JPanel();
        jbCamboriu = new javax.swing.JButton();
        panelPaquete = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fechaPartida = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        fechaRegreso = new com.toedter.calendar.JDateChooser();
        tfAlojamiento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfCapacidad = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfHabitaciones = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfPrecioNoche = new javax.swing.JTextField();
        checkIn = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        checkOut = new com.toedter.calendar.JDateChooser();
        tfMenu = new javax.swing.JTextField();
        tfPorcentaje = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfTransporte = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tfCosto = new javax.swing.JTextField();
        jbVolver = new javax.swing.JButton();
        jbMendoza = new javax.swing.JButton();
        jbBariloche = new javax.swing.JButton();
        panelPresupuesto = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tfPresupuesto = new javax.swing.JTextField();
        panelPasajeros = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jrbSI = new javax.swing.JRadioButton();
        jrbNO = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jsMayores = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jsMenores = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jsMenores2 = new javax.swing.JSpinner();
        jbConfirmarCantPasajeros = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbConfirmarCompra = new javax.swing.JButton();
        jbBuenosAires = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        tfDocumento = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        tfCorreo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jcbMedioPago = new javax.swing.JComboBox<>();
        jbConfirmarCliente = new javax.swing.JButton();
        jbJujuy = new javax.swing.JButton();
        jbIguazú = new javax.swing.JButton();
        jbGranado = new javax.swing.JButton();
        jbMarPlata = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField3.setText("jTextField3");

        setBackground(new java.awt.Color(39, 134, 188));
        setPreferredSize(new java.awt.Dimension(1045, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelGeneral.setBackground(new java.awt.Color(39, 134, 188));

        jbCamboriu.setBackground(new java.awt.Color(153, 216, 90));
        jbCamboriu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbCamboriu.setForeground(new java.awt.Color(0, 0, 0));
        jbCamboriu.setText("CAMBORIU");
        jbCamboriu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamboriuActionPerformed(evt);
            }
        });

        panelPaquete.setBackground(new java.awt.Color(39, 134, 188));
        panelPaquete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPaquete.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DESTINO");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALOJAMIENTO");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHECK IN");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PENSIÓN");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TRANSPORTE");

        tfDestino.setBackground(new java.awt.Color(255, 255, 255));
        tfDestino.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("FECHA DE PARTIDA");

        fechaPartida.setBackground(new java.awt.Color(255, 255, 255));
        fechaPartida.setForeground(new java.awt.Color(0, 0, 0));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("FECHA DE REGRESO");

        fechaRegreso.setBackground(new java.awt.Color(255, 255, 255));
        fechaRegreso.setForeground(new java.awt.Color(0, 0, 0));

        tfAlojamiento.setBackground(new java.awt.Color(255, 255, 255));
        tfAlojamiento.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CAPACIDAD");

        tfCapacidad.setBackground(new java.awt.Color(255, 255, 255));
        tfCapacidad.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("HABITACIONES");

        tfHabitaciones.setBackground(new java.awt.Color(255, 255, 255));
        tfHabitaciones.setForeground(new java.awt.Color(0, 0, 0));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("COSTO POR NOCHE");

        tfPrecioNoche.setBackground(new java.awt.Color(255, 255, 255));
        tfPrecioNoche.setForeground(new java.awt.Color(0, 0, 0));

        checkIn.setBackground(new java.awt.Color(255, 255, 255));
        checkIn.setForeground(new java.awt.Color(0, 0, 0));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CHECK OUT");

        checkOut.setBackground(new java.awt.Color(255, 255, 255));
        checkOut.setForeground(new java.awt.Color(0, 0, 0));

        tfMenu.setBackground(new java.awt.Color(255, 255, 255));
        tfMenu.setForeground(new java.awt.Color(0, 0, 0));

        tfPorcentaje.setBackground(new java.awt.Color(255, 255, 255));
        tfPorcentaje.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PORCENTAJE");

        tfTransporte.setBackground(new java.awt.Color(255, 255, 255));
        tfTransporte.setForeground(new java.awt.Color(0, 0, 0));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("COSTO");

        tfCosto.setBackground(new java.awt.Color(255, 255, 255));
        tfCosto.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelPaqueteLayout = new javax.swing.GroupLayout(panelPaquete);
        panelPaquete.setLayout(panelPaqueteLayout);
        panelPaqueteLayout.setHorizontalGroup(
            panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelPaqueteLayout.createSequentialGroup()
                                    .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                    .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel21))
                                    .addGap(16, 16, 16))
                                .addComponent(tfAlojamiento)))
                        .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fechaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel18)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fechaRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                                        .addComponent(tfHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPrecioNoche, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelPaqueteLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkOut, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(tfPorcentaje)
                                    .addComponent(tfCosto))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPaqueteLayout.setVerticalGroup(
            panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPaqueteLayout.createSequentialGroup()
                            .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addComponent(jLabel16))
                            .addGap(20, 20, 20))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPaqueteLayout.createSequentialGroup()
                            .addComponent(fechaRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(panelPaqueteLayout.createSequentialGroup()
                        .addComponent(fechaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAlojamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(tfHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfPrecioNoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(checkIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(checkOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(panelPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jbVolver.setBackground(new java.awt.Color(51, 255, 153));
        jbVolver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(0, 0, 0));
        jbVolver.setText("VOLVER");
        jbVolver.setPreferredSize(new java.awt.Dimension(141, 25));
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jbMendoza.setBackground(new java.awt.Color(153, 216, 90));
        jbMendoza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbMendoza.setForeground(new java.awt.Color(0, 0, 0));
        jbMendoza.setText("MENDOZA");
        jbMendoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMendozaActionPerformed(evt);
            }
        });

        jbBariloche.setBackground(new java.awt.Color(153, 216, 90));
        jbBariloche.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbBariloche.setForeground(new java.awt.Color(0, 0, 0));
        jbBariloche.setText("BARILOCHE");
        jbBariloche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBarilocheActionPerformed(evt);
            }
        });

        panelPresupuesto.setBackground(new java.awt.Color(28, 95, 134));
        panelPresupuesto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("PRESUPUESTO");

        tfPresupuesto.setBackground(new java.awt.Color(255, 255, 255));
        tfPresupuesto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelPresupuestoLayout = new javax.swing.GroupLayout(panelPresupuesto);
        panelPresupuesto.setLayout(panelPresupuestoLayout);
        panelPresupuestoLayout.setHorizontalGroup(
            panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresupuestoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addComponent(tfPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        panelPresupuestoLayout.setVerticalGroup(
            panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresupuestoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPresupuestoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPasajeros.setBackground(new java.awt.Color(39, 134, 188));
        panelPasajeros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("¿PAQUETE INDIVIDUAL?");

        jrbSI.setBackground(new java.awt.Color(28, 95, 134));
        jrbSI.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbSI.setForeground(new java.awt.Color(255, 255, 255));
        jrbSI.setText("SI");
        jrbSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSIActionPerformed(evt);
            }
        });

        jrbNO.setBackground(new java.awt.Color(28, 95, 134));
        jrbNO.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrbNO.setForeground(new java.awt.Color(255, 255, 255));
        jrbNO.setText("NO");
        jrbNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNOActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CANTIDAD DE MAYORES (INCLÚYENDOSE)");

        jsMayores.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsMayores.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CANTIDAD DE NIÑOS (MAYORES DE 10 AÑOS)");

        jsMenores.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsMenores.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CANTIDAD DE NIÑOS (MENORES DE 10 AÑOS)");

        jsMenores2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsMenores2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jbConfirmarCantPasajeros.setBackground(new java.awt.Color(247, 151, 91));
        jbConfirmarCantPasajeros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbConfirmarCantPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmarCantPasajeros.setText("CONFIRMAR");
        jbConfirmarCantPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarCantPasajerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPasajerosLayout = new javax.swing.GroupLayout(panelPasajeros);
        panelPasajeros.setLayout(panelPasajerosLayout);
        panelPasajerosLayout.setHorizontalGroup(
            panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajerosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPasajerosLayout.createSequentialGroup()
                        .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPasajerosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbSI, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPasajerosLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jsMayores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPasajerosLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jrbNO, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelPasajerosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsMenores, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPasajerosLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jsMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPasajerosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmarCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        panelPasajerosLayout.setVerticalGroup(
            panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajerosLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jrbSI)
                    .addComponent(jrbNO))
                .addGap(18, 18, 18)
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jsMayores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jsMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(panelPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jsMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jbConfirmarCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CANTIDAD DE PASAJEROS");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("DATOS DEL PASAJERO");

        jbConfirmarCompra.setBackground(new java.awt.Color(51, 255, 153));
        jbConfirmarCompra.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbConfirmarCompra.setForeground(new java.awt.Color(0, 0, 0));
        jbConfirmarCompra.setText("CONFIRMAR COMPRA");
        jbConfirmarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarCompraActionPerformed(evt);
            }
        });

        jbBuenosAires.setBackground(new java.awt.Color(153, 216, 90));
        jbBuenosAires.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbBuenosAires.setForeground(new java.awt.Color(0, 0, 0));
        jbBuenosAires.setText("BUENOS AIRES");
        jbBuenosAires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuenosAiresActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("DATOS DEL PAQUETE");

        panelCliente.setBackground(new java.awt.Color(39, 134, 188));
        panelCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("NOMBRE");

        tfNombre.setBackground(new java.awt.Color(255, 255, 255));
        tfNombre.setForeground(new java.awt.Color(0, 0, 0));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("APELLIDO");

        tfApellido.setBackground(new java.awt.Color(255, 255, 255));
        tfApellido.setForeground(new java.awt.Color(0, 0, 0));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("DOCUMENTO");

        tfDocumento.setBackground(new java.awt.Color(255, 255, 255));
        tfDocumento.setForeground(new java.awt.Color(0, 0, 0));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("CORREO");

        tfCorreo.setBackground(new java.awt.Color(255, 255, 255));
        tfCorreo.setForeground(new java.awt.Color(0, 0, 0));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("TELÉFONO");

        tfTelefono.setBackground(new java.awt.Color(255, 255, 255));
        tfTelefono.setForeground(new java.awt.Color(0, 0, 0));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("MEDIO DE PAGO");

        jcbMedioPago.setBackground(new java.awt.Color(255, 255, 255));
        jcbMedioPago.setForeground(new java.awt.Color(0, 0, 0));

        jbConfirmarCliente.setBackground(new java.awt.Color(247, 151, 91));
        jbConfirmarCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbConfirmarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jbConfirmarCliente.setText("CONFIRMAR");
        jbConfirmarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNombre)
                            .addComponent(tfApellido)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfTelefono)
                            .addComponent(tfDocumento)
                            .addComponent(jcbMedioPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jbConfirmarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(139, Short.MAX_VALUE))))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jcbMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConfirmarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jbJujuy.setBackground(new java.awt.Color(153, 216, 90));
        jbJujuy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbJujuy.setForeground(new java.awt.Color(0, 0, 0));
        jbJujuy.setText("JUJUY");
        jbJujuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJujuyActionPerformed(evt);
            }
        });

        jbIguazú.setBackground(new java.awt.Color(153, 216, 90));
        jbIguazú.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbIguazú.setForeground(new java.awt.Color(0, 0, 0));
        jbIguazú.setText("CTAS. DEL IGUAZÚ");
        jbIguazú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIguazúActionPerformed(evt);
            }
        });

        jbGranado.setBackground(new java.awt.Color(153, 216, 90));
        jbGranado.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jbGranado.setForeground(new java.awt.Color(0, 0, 0));
        jbGranado.setText("GRAMADO Y CANELA");
        jbGranado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGranadoActionPerformed(evt);
            }
        });

        jbMarPlata.setBackground(new java.awt.Color(153, 216, 90));
        jbMarPlata.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbMarPlata.setForeground(new java.awt.Color(0, 0, 0));
        jbMarPlata.setText("MAR DE PLATA");
        jbMarPlata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMarPlataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jbConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGeneralLayout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelGeneralLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jbCamboriu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jbBariloche, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jbMendoza, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jbGranado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGeneralLayout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addComponent(jbIguazú, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jbMarPlata, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(jbBuenosAires, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jbJujuy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10)
                        .addComponent(panelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelGeneralLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel22)
                            .addGap(391, 391, 391)
                            .addComponent(jLabel7))
                        .addGroup(panelGeneralLayout.createSequentialGroup()
                            .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(panelPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGeneralLayout.createSequentialGroup()
                            .addGap(320, 320, 320)
                            .addComponent(panelPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap(796, Short.MAX_VALUE)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGeneralLayout.createSequentialGroup()
                    .addGap(0, 35, Short.MAX_VALUE)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbCamboriu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBariloche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbMendoza, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbGranado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbIguazú, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbMarPlata, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuenosAires, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbJujuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(15, 15, 15)
                    .addComponent(jLabel10)
                    .addGap(0, 0, 0)
                    .addComponent(panelPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(jLabel7))
                    .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(panelPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(panelPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 101, Short.MAX_VALUE)))
        );

        getContentPane().add(panelGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarClienteActionPerformed

    private void jbConfirmarCantPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarCantPasajerosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarCantPasajerosActionPerformed

    private void jrbSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSIActionPerformed

    private void jrbNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbNOActionPerformed

    private void jbConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbConfirmarCompraActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbCamboriuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamboriuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCamboriuActionPerformed

    private void jbIguazúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIguazúActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbIguazúActionPerformed

    private void jbBarilocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBarilocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBarilocheActionPerformed

    private void jbMarPlataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMarPlataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMarPlataActionPerformed

    private void jbMendozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMendozaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMendozaActionPerformed

    private void jbBuenosAiresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuenosAiresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuenosAiresActionPerformed

    private void jbGranadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGranadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbGranadoActionPerformed

    private void jbJujuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJujuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbJujuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser checkIn;
    private com.toedter.calendar.JDateChooser checkOut;
    private com.toedter.calendar.JDateChooser fechaPartida;
    private com.toedter.calendar.JDateChooser fechaRegreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jbBariloche;
    private javax.swing.JButton jbBuenosAires;
    private javax.swing.JButton jbCamboriu;
    private javax.swing.JButton jbConfirmarCantPasajeros;
    private javax.swing.JButton jbConfirmarCliente;
    private javax.swing.JButton jbConfirmarCompra;
    private javax.swing.JButton jbGranado;
    private javax.swing.JButton jbIguazú;
    private javax.swing.JButton jbJujuy;
    private javax.swing.JButton jbMarPlata;
    private javax.swing.JButton jbMendoza;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox<String> jcbMedioPago;
    private javax.swing.JRadioButton jrbNO;
    private javax.swing.JRadioButton jrbSI;
    private javax.swing.JSpinner jsMayores;
    private javax.swing.JSpinner jsMenores;
    private javax.swing.JSpinner jsMenores2;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelPaquete;
    private javax.swing.JPanel panelPasajeros;
    private javax.swing.JPanel panelPresupuesto;
    private javax.swing.JTextField tfAlojamiento;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCapacidad;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfCosto;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfDocumento;
    private javax.swing.JTextField tfHabitaciones;
    private javax.swing.JTextField tfMenu;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPorcentaje;
    private javax.swing.JTextField tfPrecioNoche;
    private javax.swing.JTextField tfPresupuesto;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfTransporte;
    // End of variables declaration//GEN-END:variables
private void cargarComboBox(){
    jcbMedioPago.addItem("Tarjeta de débito");
    jcbMedioPago.addItem("Tarjeta de crédito");
    jcbMedioPago.addItem("Efectivo");
    jcbMedioPago.addItem("Mercado Pago");
    
}

}
