/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import AccesoADatos.AlojamientoData;
import AccesoADatos.MenuData;
import AccesoADatos.PaqueteData;
import AccesoADatos.TransporteData;
import Entidades.Alojamiento;
import Entidades.Estadia;
import Entidades.MenuPension;
import Entidades.Paquete;
import Entidades.Pasaje;
import Entidades.Transporte;
import static Vistas.PasajeView.pasajeSeleccionado;
import static Vistas.PasajeView.transporteSeleccionado;
import static Vistas.seleccionarMenu.menuSeleccionado;
import static Vistas.vistaDestino.destinoSeleccionado;
import static Vistas.vistaDestino.origenSeleccionado;
import static Vistas.vistaDestino.fechFin;
import static Vistas.vistaDestino.fechInicio;
import static Vistas.vistaEstadia.alojamientoSeleccionado;
import static Vistas.vistaEstadia.estadiaSeleccionada;
import static Vistas.seleccionarMenu.menuSeleccionado;
import static Vistas.vistaCliente.clienteSeleccionado;
import static Vistas.vistaCliente.medioPago;
import static Vistas.vistaDestino.destinoSeleccionado;
import static Vistas.vistaDestino.origenSeleccionado;
import static Vistas.vistaDestino.temporada;
import static Vistas.vistaEstadia.alojamientoSeleccionado;
import static Vistas.vistaEstadia.estadiaSeleccionada;
import com.toedter.calendar.JDateChooser;
import java.awt.Component;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.ButtonGroup;

/**
 *
 * @author Lourdes
 */
public class vistaPaquetePersonalizado extends javax.swing.JInternalFrame {
 private final AlojamientoData alData = new AlojamientoData();
 private final MenuData menuData = new MenuData();
 private final TransporteData tranData = new TransporteData();
 private final PaqueteData paqData = new PaqueteData();
 private boolean paqueteModificado = false;
    /**
     * Creates new form vistaPaquetePersonalizado
     */
    public vistaPaquetePersonalizado() {
        initComponents();
        ButtonGroup grupoIndividual = new ButtonGroup();
        grupoIndividual.add(jrbIndividualSI);
        grupoIndividual.add(jrbIndividualNo);
        
        ButtonGroup grupoNinios = new ButtonGroup();
        grupoNinios.add(jrbMenoresNo);
        grupoNinios.add(jrbMenoresSi);
        
        bloquearCampos(contenedorInfo);
        bloquearCampos(panelCantPasajeros);
        bloquearCampos(panelCantMenores);
        jbConfirmar.setEnabled(false);
        jbConfirmarPaquete.setEnabled(false);
        
        cargarComboBox();
        cargarDatos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDestino = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        tfCostoEstadia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCostoMenu = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfCostoTransporte = new javax.swing.JTextField();
        jcbEstadia = new javax.swing.JComboBox<>();
        jcbTransporte = new javax.swing.JComboBox<>();
        jcbMenu = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tfCapacidad = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jdCheckin = new com.toedter.calendar.JDateChooser();
        jdCheckout = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        tfHabitaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelPasajeroIndividual = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrbIndividualSI = new javax.swing.JRadioButton();
        jrbIndividualNo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        panelCantPasajeros = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jsCantMayores = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jrbMenoresSi = new javax.swing.JRadioButton();
        jrbMenoresNo = new javax.swing.JRadioButton();
        panelCantMenores = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jsMenores1 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jsMenores2 = new javax.swing.JSpinner();
        jbConfirmarPaquete = new javax.swing.JButton();
        jbDescartarPaquete = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        tfCostoTotal = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Destino:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Estadía:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Menú:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Transporte:");

        tfDestino.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("FECHA INICIO:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setText("FECHA FIN:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("COSTO:");

        tfCostoEstadia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("COSTO:");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("COSTO:");

        tfCostoTransporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jcbEstadia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbEstadiaItemStateChanged(evt);
            }
        });
        jcbEstadia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEstadiaActionPerformed(evt);
            }
        });

        jcbTransporte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTransporteItemStateChanged(evt);
            }
        });
        jcbTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTransporteActionPerformed(evt);
            }
        });

        jcbMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbMenuItemStateChanged(evt);
            }
        });
        jcbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMenuActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("CAPACIDAD");

        tfCapacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbModificar.setText("MODIFICAR");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("CONFIRMAR CAMBIOS");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel19.setText("CHECK-IN");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel20.setText("CHECK-OUT");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setText("HABITACIONES");

        tfHabitaciones.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout contenedorInfoLayout = new javax.swing.GroupLayout(contenedorInfo);
        contenedorInfo.setLayout(contenedorInfoLayout);
        contenedorInfoLayout.setHorizontalGroup(
            contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInfoLayout.createSequentialGroup()
                        .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contenedorInfoLayout.createSequentialGroup()
                                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(jbConfirmar))
                            .addGroup(contenedorInfoLayout.createSequentialGroup()
                                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbTransporte, 0, 210, Short.MAX_VALUE)
                                    .addComponent(jcbMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCostoMenu)
                                    .addComponent(tfCostoTransporte))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(contenedorInfoLayout.createSequentialGroup()
                        .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbEstadia, javax.swing.GroupLayout.Alignment.LEADING, 0, 210, Short.MAX_VALUE)
                            .addComponent(tfDestino, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenedorInfoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contenedorInfoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(3, 3, 3)
                                .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(contenedorInfoLayout.createSequentialGroup()
                                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contenedorInfoLayout.createSequentialGroup()
                                        .addComponent(jdCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(contenedorInfoLayout.createSequentialGroup()
                                        .addComponent(tfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorInfoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(2, 2, 2)
                        .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(contenedorInfoLayout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfHabitaciones))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contenedorInfoLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCostoEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        contenedorInfoLayout.setVerticalGroup(
            contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorInfoLayout.createSequentialGroup()
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenedorInfoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(tfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(tfHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jdCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(tfCostoEstadia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfCostoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(tfCostoTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(contenedorInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("PAQUETE ELEGIDO");

        panelPasajeroIndividual.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("INDIVIDUAL:");

        jrbIndividualSI.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbIndividualSI.setText("SI");
        jrbIndividualSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIndividualSIActionPerformed(evt);
            }
        });

        jrbIndividualNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbIndividualNo.setText("NO");
        jrbIndividualNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIndividualNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPasajeroIndividualLayout = new javax.swing.GroupLayout(panelPasajeroIndividual);
        panelPasajeroIndividual.setLayout(panelPasajeroIndividualLayout);
        panelPasajeroIndividualLayout.setHorizontalGroup(
            panelPasajeroIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajeroIndividualLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jLabel7)
                .addGap(46, 46, 46)
                .addComponent(jrbIndividualSI, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jrbIndividualNo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        panelPasajeroIndividualLayout.setVerticalGroup(
            panelPasajeroIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPasajeroIndividualLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelPasajeroIndividualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jrbIndividualSI)
                    .addComponent(jrbIndividualNo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("PASAJEROS:");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("CANTIDAD DE MAYORES:");

        jsCantMayores.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsCantMayores.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("NIÑOS: ");

        jrbMenoresSi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbMenoresSi.setText("SI");
        jrbMenoresSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMenoresSiActionPerformed(evt);
            }
        });

        jrbMenoresNo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jrbMenoresNo.setText("NO");
        jrbMenoresNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMenoresNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCantPasajerosLayout = new javax.swing.GroupLayout(panelCantPasajeros);
        panelCantPasajeros.setLayout(panelCantPasajerosLayout);
        panelCantPasajerosLayout.setHorizontalGroup(
            panelCantPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantPasajerosLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsCantMayores, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(jrbMenoresSi)
                .addGap(48, 48, 48)
                .addComponent(jrbMenoresNo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCantPasajerosLayout.setVerticalGroup(
            panelCantPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantPasajerosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCantPasajerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jsCantMayores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbMenoresNo)
                    .addComponent(jLabel9)
                    .addComponent(jrbMenoresSi))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel16.setText("NIÑOS +10 AÑOS:");

        jsMenores1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsMenores1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel17.setText("NIÑOS -10 AÑOS:");

        jsMenores2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jsMenores2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout panelCantMenoresLayout = new javax.swing.GroupLayout(panelCantMenores);
        panelCantMenores.setLayout(panelCantMenoresLayout);
        panelCantMenoresLayout.setHorizontalGroup(
            panelCantMenoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantMenoresLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel16)
                .addGap(54, 54, 54)
                .addComponent(jsMenores1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCantMenoresLayout.setVerticalGroup(
            panelCantMenoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCantMenoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCantMenoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jsMenores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jsMenores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jbConfirmarPaquete.setText("CONFIRMAR PAQUETE");
        jbConfirmarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarPaqueteActionPerformed(evt);
            }
        });

        jbDescartarPaquete.setText("DESCARTAR PAQUETE");
        jbDescartarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDescartarPaqueteActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("COSTO TOTAL DEL PAQUETE:");

        tfCostoTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfCostoTotal.setText("COSTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelCantPasajeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(panelCantMenores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbConfirmarPaquete)
                                .addGap(57, 57, 57)
                                .addComponent(jbDescartarPaquete)
                                .addGap(208, 208, 208))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelPasajeroIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contenedorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPasajeroIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCantMenores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfCostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConfirmarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDescartarPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbEstadiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbEstadiaItemStateChanged
      mostrarDatosEstadia();
    }//GEN-LAST:event_jcbEstadiaItemStateChanged

    private void jcbMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbMenuItemStateChanged
          mostrarDatosMenu();
    }//GEN-LAST:event_jcbMenuItemStateChanged

    private void jcbTransporteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTransporteItemStateChanged
        mostrarDatosTransporte();
    }//GEN-LAST:event_jcbTransporteItemStateChanged

    private void jcbEstadiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEstadiaActionPerformed
         mostrarDatosEstadia();
    }//GEN-LAST:event_jcbEstadiaActionPerformed

    private void jcbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMenuActionPerformed
         mostrarDatosMenu();
    }//GEN-LAST:event_jcbMenuActionPerformed

    private void jcbTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTransporteActionPerformed
         mostrarDatosTransporte();
    }//GEN-LAST:event_jcbTransporteActionPerformed

    private void jrbIndividualSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIndividualSIActionPerformed
        if(jrbIndividualSI.isSelected()){
            jbConfirmarPaquete.setEnabled(true);
        }else{
            desbloquearCampos(panelCantPasajeros);
        }
    }//GEN-LAST:event_jrbIndividualSIActionPerformed

    private void jrbIndividualNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIndividualNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbIndividualNoActionPerformed

    private void jrbMenoresSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMenoresSiActionPerformed
        if(jrbMenoresSi.isSelected()){
            desbloquearCampos(panelCantMenores);
        }else{
            jbConfirmarPaquete.setEnabled(true);
        }
    }//GEN-LAST:event_jrbMenoresSiActionPerformed

    private void jrbMenoresNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMenoresNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbMenoresNoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        jbConfirmar.setEnabled(true);
        jbModificar.setEnabled(false);
        desbloquearCamposEspecificos();
        paqueteModificado = true;
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        if(validarCamposVacios(contenedorInfo)){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos.");
            return;
        }else{
            confirmarCambios();
            JOptionPane.showMessageDialog(this, "Se confirmaron los cambios en el paquete.");
            jbConfirmar.setEnabled(false);
            bloquearCampos(contenedorInfo);
        }
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbConfirmarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarPaqueteActionPerformed
       crearPaquete();
       JOptionPane.showMessageDialog(this, "Paquete creado con éxito.");
       dispose();
       
    }//GEN-LAST:event_jbConfirmarPaqueteActionPerformed

    private void jbDescartarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDescartarPaqueteActionPerformed
       dispose();
    }//GEN-LAST:event_jbDescartarPaqueteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorInfo;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JButton jbConfirmarPaquete;
    private javax.swing.JButton jbDescartarPaquete;
    private javax.swing.JButton jbModificar;
    private javax.swing.JComboBox<Alojamiento> jcbEstadia;
    private javax.swing.JComboBox<String> jcbMenu;
    private javax.swing.JComboBox<String> jcbTransporte;
    private com.toedter.calendar.JDateChooser jdCheckin;
    private com.toedter.calendar.JDateChooser jdCheckout;
    private javax.swing.JRadioButton jrbIndividualNo;
    private javax.swing.JRadioButton jrbIndividualSI;
    private javax.swing.JRadioButton jrbMenoresNo;
    private javax.swing.JRadioButton jrbMenoresSi;
    private javax.swing.JSpinner jsCantMayores;
    private javax.swing.JSpinner jsMenores1;
    private javax.swing.JSpinner jsMenores2;
    private javax.swing.JPanel panelCantMenores;
    private javax.swing.JPanel panelCantPasajeros;
    private javax.swing.JPanel panelPasajeroIndividual;
    private javax.swing.JTextField tfCapacidad;
    private javax.swing.JTextField tfCostoEstadia;
    private javax.swing.JTextField tfCostoMenu;
    private javax.swing.JTextField tfCostoTotal;
    private javax.swing.JTextField tfCostoTransporte;
    private javax.swing.JTextField tfDestino;
    private javax.swing.JTextField tfHabitaciones;
    // End of variables declaration//GEN-END:variables


 
private boolean validarCamposVacios(JPanel jpanel) {
    for (Component c : jpanel.getComponents()) {
        if (c instanceof JTextField) {
            JTextField t = (JTextField) c;
            if (t.getText().trim().isEmpty()) {  // Verifica si el campo está vacío
                return true;
            }
        }
        
        if (c instanceof JComboBox) {
            JComboBox<?> combo = (JComboBox<?>) c;
            if (combo.getSelectedItem() == null || combo.getSelectedIndex() == -1) { // Verifica si no hay selección
                return true;
            }
        }
        
        if(c instanceof JDateChooser){
           JDateChooser d = (JDateChooser) c;
           if(d.getDate() == null){
               return true;
            }
        }
        
    }
    return false; // No hay campos vacíos
}
 
 private void bloquearCampos(JPanel jpanel) {
    for (Component c : jpanel.getComponents()) {
        if (c instanceof JTextField) {
            JTextField t = (JTextField) c;
            t.setEnabled(false); // Deshabilita el JTextField
        }
        
        
        if (c instanceof JComboBox) {
            JComboBox<?> combo = (JComboBox<?>) c;
            combo.setEnabled(false); // Deshabilita el JComboBox
        }
        
        if (c instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox) c;
            checkBox.setEnabled(false); // Deshabilita el JCheckBox
        }
        
        if(c instanceof JDateChooser) {
            JDateChooser t = (JDateChooser) c;
            t.setEnabled(false);
        }
        
    }
    
     
}
 
  private void desbloquearCampos(JPanel jpanel) {
    for (Component c : jpanel.getComponents()) {
        if (c instanceof JTextField) {
            JTextField t = (JTextField) c;
            t.setEnabled(true); // habilita el JTextField
        }
        
        
        if (c instanceof JComboBox) {
            JComboBox<?> combo = (JComboBox<?>) c;
            combo.setEnabled(true); // habilita el JComboBox
        }
        
        if (c instanceof JCheckBox) {
            JCheckBox checkBox = (JCheckBox) c;
            checkBox.setEnabled(true); // habilita el JCheckBox
        }
        
        if(c instanceof JDateChooser) {
            JDateChooser t = (JDateChooser) c;
            t.setEnabled(true);
        }
        
    }
}
  

  
  private void desbloquearCamposEspecificos(){
      dcFechaFin.setEnabled(true);
      dcFechaInicio.setEnabled(true);
      jcbEstadia.setEnabled(true);
      jcbMenu.setEnabled(true);
      jcbTransporte.setEnabled(true);
  }
  
  private void cargarDatos(){
      try{
          
          tfDestino.setText(destinoSeleccionado.toString());
          dcFechaInicio.setDate(fechInicio);
          dcFechaFin.setDate(fechFin);
          
          jcbEstadia.setSelectedItem(alojamientoSeleccionado);
          tfCapacidad.setText(String.valueOf(alojamientoSeleccionado.getCapacidad()));
          tfHabitaciones.setText(String.valueOf(alojamientoSeleccionado.getNroAmbientes()));
          jdCheckin.setDate((estadiaSeleccionada.getFechaCheckIn()));
          jdCheckout.setDate((estadiaSeleccionada.getFechaCheckOut()));
          tfCostoEstadia.setText(String.valueOf(estadiaSeleccionada.getTotal()));
          
          jcbMenu.setSelectedItem(menuSeleccionado);
          tfCostoMenu.setText(String.valueOf(menuSeleccionado.getPorcentaje()));
          
          jcbTransporte.setSelectedItem(transporteSeleccionado);
          tfCostoTransporte.setText(String.valueOf(transporteSeleccionado.getCosto()));
          
          
      }catch(NullPointerException ex){
          JOptionPane.showMessageDialog(this, "ERROR");
      }catch(ClassCastException | NumberFormatException ex){
         JOptionPane.showMessageDialog(this, "Error al cargar datos. " +ex);
     }
  }
  

      private void cargarComboBox(){
   jcbEstadia.removeAllItems();
   int capacidad = Integer.parseInt(tfCapacidad.getText());
   
   List<Alojamiento> lista = alData.buscarAlojamientoCapacidad(capacidad,destinoSeleccionado.getIdDestino());
   
   if(lista.isEmpty()){
       JOptionPane.showMessageDialog(this, "No hay alojamientos disponibles.");
   }else{
   for(Alojamiento alo : lista){ //el 1 se intercambia por getDestino.
       jcbEstadia.addItem(alo);
   } 
   
   }
      }
      
      
  private void confirmarCambios(){
     try{
      Date inicio = (Date) jdCheckin.getDate();
      Date fin =  (Date) jdCheckout.getDate();
      double Total = estadiaSeleccionada.getTotal(); 
      alojamientoSeleccionado = (Alojamiento) jcbEstadia.getSelectedItem();
      estadiaSeleccionada = new Estadia(alojamientoSeleccionado, inicio, fin, Total);
      
      String tipomenu = (String) jcbMenu.getSelectedItem();
      double costomenu = Double.parseDouble(tfCostoMenu.getText());
      menuSeleccionado = new MenuPension(tipomenu, costomenu);
      
      
      int asiento = pasajeSeleccionado.getAsiento();
      String tipoTransporte = (String) jcbTransporte.getSelectedItem();
      double costoTransporte = Double.parseDouble(tfCostoTransporte.getText());
      transporteSeleccionado = new Transporte(tipoTransporte,costoTransporte);
       pasajeSeleccionado = new Pasaje( transporteSeleccionado,origenSeleccionado,destinoSeleccionado,asiento);
       
     }catch(NullPointerException ex){
         JOptionPane.showMessageDialog(this, "Error. Hay datos en NULL. " +ex);
     }catch(ClassCastException | NumberFormatException ex){
         JOptionPane.showMessageDialog(this, "Error al actualizar datos. " +ex);
     }
  }
  
  
  private void mostrarDatosEstadia(){
      Alojamiento aloj = (Alojamiento) jcbEstadia.getSelectedItem();
      tfCapacidad.setText(String.valueOf(aloj.getCapacidad())); 
      tfHabitaciones.setText(String.valueOf(aloj.getNroAmbientes())); 
      tfCostoEstadia.setText(String.valueOf(aloj.getPrecioPorNoche())); 
  }
  
  private void mostrarDatosMenu(){
      String tipo = (String) jcbMenu.getSelectedItem();
      MenuPension menu = menuData.buscarMenuPorTipo(tipo);
      
      tfCostoMenu.setText(String.valueOf(menu.getPorcentaje()));
  }
  
  private void mostrarDatosTransporte(){
      String tipo = (String) jcbTransporte.getSelectedItem();
       tfCostoTransporte.setText(String.valueOf(tranData.obtenerCostoPorTipo(tipo)));
  }
  
  
private void crearPaquete(){
    try{
    int cantPasajerosAdultos =1;
    int cantPasajerosNinios =0;
    int cantPasajerosNiniosMenores =0;
   
    
    double totalEstadia = estadiaSeleccionada.getTotal();
    double totalMenu = menuSeleccionado.getPorcentaje();
    double totalTransporte = transporteSeleccionado.getCosto();
    
    
    if(!jrbIndividualSI.isSelected()){
        cantPasajerosAdultos = (int) jsCantMayores.getValue();
    }
    if(jrbMenoresSi.isSelected()){
        cantPasajerosNinios = (int) jsMenores1.getValue();
        cantPasajerosNiniosMenores= (int) jsMenores2.getValue();
    }
    
    int totalPasajeros = cantPasajerosAdultos + cantPasajerosNinios + cantPasajerosNiniosMenores;
    double costoBase = totalEstadia + totalTransporte;
    double costoMenu = costoBase * totalMenu;
    double precioTotal = (costoBase + costoMenu) * totalPasajeros;
    double penalizacion = 0.10 * totalPasajeros;
    if (paqueteModificado) {
       precioTotal *= penalizacion;
    }
    
    
  
    
    Paquete paquete = new Paquete(clienteSeleccionado,estadiaSeleccionada,
            pasajeSeleccionado,menuSeleccionado, origenSeleccionado, destinoSeleccionado,fechInicio,fechFin,temporada,totalPasajeros,medioPago,
               true,false,precioTotal);
    paqData.guardarPaquete(paquete);
   }catch(NullPointerException ex){
         JOptionPane.showMessageDialog(this, "Error. Hay datos en NULL. " +ex);
   }catch(ClassCastException | NumberFormatException ex){
         JOptionPane.showMessageDialog(this, "Error al armar paquete. " +ex);
}
} 

}
